adds new section
marcobonni/Nintendo_Clone pull request #12
Opened 2023-01-16 18:05 UTC by Roberta93-web

Add news section

2023-01-17 17:21 UTC, marcobonni requested changes

2023-01-17 17:21 UTC, marcobonni commented on style.scss
> -            border-bottom: rgb(72, 72, 72, 0.2) 1px solid;
meglio come è scritto così

2023-01-17 17:21 UTC, marcobonni commented on style.scss
> -                    border-radius: 10px;
anche qui

2023-01-17 17:21 UTC, marcobonni commented on style.scss
> -
sicura di aver fatto git pull prima di fare il branch? questo è quello che ho fatto io. se ti accetto la pull request cancello tutto quello che ho fatto io

2023-01-17 17:21 UTC, marcobonni commented on style.scss
> +
questi spazi non servono

2023-01-18 20:00 UTC, Roberta93-web commented on style.scss
> -            border-bottom: rgb(72, 72, 72, 0.2) 1px solid;
fatto

2023-01-18 20:06 UTC, Roberta93-web commented on style.scss
> -                    border-radius: 10px;
fatto

2023-01-18 20:28 UTC, Roberta93-web commented
Aggiunto modifiche

2023-01-19 02:15 UTC, marcobonni approved these changes

2023-01-19 02:15 UTC, merged